#!/bin/sh
volumePath=$1
resourcePath=$2

cp -R "$resourcePath/gfxshared/IOAccelerator2D.plugin" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/gfxshared/IOAcceleratorFamily2.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/gfxshared/IONDRVSupport.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/gfxshared/IOGraphicsFamily.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/gfxshared/GPUSupport.framework" "$volumePath/System/Library/PrivateFrameworks/"
cp -R "$resourcePath/gfxshared/AppleGVA.framework" "$volumePath/System/Library/PrivateFrameworks/"
cp -R "$resourcePath/gfxshared/OpenGL.framework" "$volumePath/System/Library/Frameworks/"
cp -R "$resourcePath/gfxshared/AppleGraphicsControl.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/gfxshared/AppleGraphicsPowerManagement.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/gfxshared/AppleMCCSControl.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/gfxshared/CoreDisplay.framework" "$volumePath/System/Library/Frameworks/"
cp "$resourcePath/gfxshared/SkyLight" "$volumePath/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/"

chmod -R 755 "$volumePath/System/Library/Frameworks/OpenGL.framework"
chown -R 0:0 "$volumePath/System/Library/Frameworks/OpenGL.framework"
chmod -R 755 "$volumePath/System/Library/PrivateFrameworks/SkyLight.framework"
chown -R 0:0 "$volumePath/System/Library/PrivateFrameworks/SkyLight.framework"
chmod -R 755 "$volumePath/System/Library/PrivateFrameworks/GPUSupport.framework"
chown -R 0:0 "$volumePath/System/Library/PrivateFrameworks/GPUSupport.framework"
chmod -R 755 "$volumePath/System/Library/PrivateFrameworks/AppleGVA.framework"
chown -R 0:0 "$volumePath/System/Library/PrivateFrameworks/AppleGVA.framework"
chmod -R 755 "$volumePath/System/Library/Frameworks/CoreDisplay.framework"
chown -R 0:0 "$volumePath/System/Library/Frameworks/CoreDisplay.framework"

cp -R "$resourcePath/legacynvidia/GeForceTesla.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacynvidia/GeForceTeslaGLDriver.bundle" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacynvidia/GeForceTeslaVADriver.bundle" "$volumePath/System/Library/Extensions/"
#cp -R "$resourcePath/legacynvidia/NDRVShim.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacynvidia/NVDANV50HalTesla.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacynvidia/NVDAResmanTesla.kext" "$volumePath/System/Library/Extensions/"
#cp -R "$resourcePath/legacynvidia/NVDAStartup.kext" "$volumePath/System/Library/Extensions/"

cp -R "$resourcePath/intelsandybridgegraphics/AppleIntelHD3000Graphics.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/intelsandybridgegraphics/AppleIntelHD3000GraphicsGA.plugin" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/intelsandybridgegraphics/AppleIntelHD3000GraphicsGLDriver.bundle" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/intelsandybridgegraphics/AppleIntelHD3000GraphicsVADriver.bundle" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/intelsandybridgegraphics/AppleIntelSNBGraphicsFB.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/intelsandybridgegraphics/AppleIntelSNBVA.bundle" "$volumePath/System/Library/Extensions/"

cp -R "$resourcePath/intelarrandalegraphics/AppleIntelFramebufferAzul.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/intelarrandalegraphics/AppleIntelFramebufferCapri.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/intelarrandalegraphics/AppleIntelHDGraphics.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/intelarrandalegraphics/AppleIntelHDGraphicsFB.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/intelarrandalegraphics/AppleIntelHDGraphicsGA.plugin" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/intelarrandalegraphics/AppleIntelHDGraphicsGLDriver.bundle" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/intelarrandalegraphics/AppleIntelHDGraphicsVADriver.bundle" "$volumePath/System/Library/Extensions/"

cp -R "$resourcePath/legacyamd/AMD2400Controller.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMD2600Controller.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMD3800Controller.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMD4600Controller.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMD4800Controller.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMD5000Controller.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMD6000Controller.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMDRadeonX3000.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMDRadeonX3000GLDriver.bundle" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMDRadeonX4000.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMDRadeonX4000GLDriver.bundle" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMDFramebuffer.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMDLegacySupport.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMDLegacyFramebuffer.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMDRadeonVADriver.bundle" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMDRadeonVADriver2.bundle" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMDShared.bundle" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/AMDSupport.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/ATIRadeonX2000.kext" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/ATIRadeonX2000GA.plugin" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/ATIRadeonX2000GLDriver.bundle" "$volumePath/System/Library/Extensions/"
cp -R "$resourcePath/legacyamd/ATIRadeonX2000VADriver.bundle" "$volumePath/System/Library/Extensions/"

chmod -R 755 "$volumePath/System/Library/Extensions/"
chown -R 0:0 "$volumePath/System/Library/Extensions/"
