#!/bin/sh
rsrcPath=$1
volPath=$2
specPath=$3
installerAppPath=$4
rm -R "$volPath/System/Installation/Packages"
cp -R "/tmp/installesd/Packages" "$volPath/System/Installation/"
cp "$installerAppPath/Contents/SharedSupport/BaseSystem.dmg" "$volPath/"
cp "$installerAppPath/Contents/SharedSupport/BaseSystem.chunklist" "$volPath/"
cp "$installerAppPath/Contents/SharedSupport/AppleDiagnostics.dmg" "$volPath/"
cp "$installerAppPath/Contents/SharedSupport/AppleDiagnostics.chunklist" "$volPath/"
cp "$rsrcPath/PlatformSupport.plist" "$volPath/System/Library/CoreServices/"
rm -R "$volPath/System/Installation/CDIS/macOS Installer.app"
cp -R "$rsrcPath/macOS Installer.app" "$volPath/System/Installation/CDIS"
rm -R "$volPath/System/Library/Frameworks/Quartz.framework"
cp -R "$rsrcPath/Quartz.framework" "$volPath/System/Library/Frameworks/"
cp "$rsrcPath/prelinkedkernel" "$volPath/System/Library/PrelinkedKernels/"
xattr -c "$volPath/System/Library/PrelinkedKernels/prelinkedkernel"
chflags uchg "$volPath/System/Library/PrelinkedKernels/prelinkedkernel"
mkdir "$volPath/System/Library/Caches"
cp -R "$rsrcPath/com.apple.kext.caches" "$volPath/System/Library/Caches/"
cp -R "$rsrcPath/LegacyUSBInjector.kext" "$volPath/Library/Extensions/"
cp -R "$rsrcPath/SIPManager.kext" "$volPath/Library/Extensions/"
chmod -R 0755 "$volPath/Library/Extensions/LegacyUSBInjector.kext"
chown -R 0:0 "$volPath/Library/Extensions/LegacyUSBInjector.kext"
chmod -R 0755 "$volPath/Library/Extensions/SIPManager.kext"
chown -R 0:0 "$volPath/Library/Extensions/SIPManager.kext"
cp -R "$rsrcPath/macOS Post Install.app" "$volPath/Applications/Utilities/"
cp "$rsrcPath/InstallerMenuAdditions.plist" "$volPath/System/Installation/CDIS/macOS Installer.app/Contents/Resources/"
cp "$specPath/OSInstall.mpkg" "$volPath/System/Installation/Packages/"
cp "$rsrcPath/prelinkedkernel" "$volPath/Applications/Utilities/macOS Post Install.app/Contents/Resources/"
rm -R "$volPath/System/Library/PrivateFrameworks/OSInstaller.framework"
cp -R "$rsrcPath/OSInstaller.framework" "$volPath/System/Library/PrivateFrameworks/"
cp -R "$rsrcPath/UtilitiesLauncher.app" "$volPath/Applications/Utilities/"
cp "$rsrcPath/com.dd1.UtilitiesLauncher.plist" "$volPath/System/Library/LaunchDaemons/"
rm -R "$volPath/System/Library/PrivateFrameworks/SystemMigration.framework"
cp -R "$rsrcPath/SystemMigration.framework" "$volPath/System/Library/PrivateFrameworks/"
rm -R "$volPath/System/Library/PrivateFrameworks/SystemMigrationUtils.framework"
cp -R "$rsrcPath/SystemMigrationUtils.framework" "$volPath/System/Library/PrivateFrameworks/"
